### ISSUE TITLE
Incompatibility in resolving namespace

### ISSUE THREAD

**Issue by k0kubun** [mruby/mruby#3200]
``` rb
$ irb
irb(main):001:0> RUBY_VERSION
=> "1.9.3"
irb(main):002:0> module Foo; module Bar; end; module File; end; end
=> nil
irb(main):003:0> module Foo::Bar; p File; end
File
=> File
```

``` rb
# mruby/mruby at 22dc84f
$ ./bin/mirb     
mirb - Embeddable Interactive Ruby Shell

> module Foo; module Bar; end; module File; end; end
 => nil
> module Foo::Bar; p File; end
Foo::File
 => Foo::File
```

I expect the last result to be `File`. Is this intentional?
If these behaviors are unified, porting existing Ruby code to mruby will become easier.

**Comment by beoran** [comment]
@matz I think this was already fixed?

**Comment by matz** [comment]
No, it's not fixed. But the recent CRuby gives
```
File
Foo::File
```
instead of
```
File
File
```
as the OP suggests. FYI, mruby gives
```
Foo::File
Foo::File
```

**Comment by christopheraue** [comment]
@matz In CRuby 2.4.1 I'm still getting 

```
File
=> File
```

Furthermore, this issue is a duplicate of the remain issue mentioned in #600: Actual nesting is used for constant lookup instead of lexical nesting.

**Comment by matz** [comment]
To implement lexical constant scoping, we need to add a member to irep structure, that means more memory.

**Comment by beoran** [comment]
What are the benefits of lexical scoping for mruby? Compatibility with CRuby is one. Also, how about the ISO standard?

Furthermore, I thought lexical scoping is done at compile time?

**Comment by christopheraue** [comment]
What about a compile flag `MRB_LEXICAL_CONST_LOOKUP`? Then you have a choice if you rather want mruby to be CRuby compatible or memory-efficient.

For me CRuby compatibility is more important since it removes an error source when switching between CRuby and mruby. I'm also thinking about the ability to plainly use gems written for CRuby in mruby. Right now I wouldn't dare to try it because I know the constant lookup is very likely to cause trouble. Just like it does when I'm porting my own code.

**Comment by matz** [comment]
I think I got the idea to address the issue with minimum memory impact (1 word per irep).
Let me try the idea.

**Comment by k0kubun** [comment]
Thank you for fixing this!

**Comment by matz** [comment]
Better late than never.
