### ISSUE TITLE
AddressSanitizer: stack-overflow mrbgems/mruby-compiler/core/codegen.c:1204

### ISSUE THREAD

**Issue by revskills** [mruby/mruby#3242]
Repro file:
```sh
Base64: +Pj4+Pj4+Pj4+Pj4+Pj4+PH4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr
KysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysr+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4//j4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+D08PDH4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+KX4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+AACAAD4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4
+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+PifiIiIIZGIiCA=
```sh
```sh
mruby 1.2.0 (2015-11-17) # stable
ASAN:DEADLYSIGNAL
=================================================================
==2865==ERROR: AddressSanitizer: stack-overflow on address 0x7fff9d462da0 (pc 0x000000696242 bp 0x7fff9d466290 sp 0x7fff9d462da0 T0)
    #0 0x696241 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1204
    #1 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #2 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #3 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #4 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #5 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #6 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #7 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #8 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #9 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #10 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #11 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #12 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #13 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #14 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #15 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #16 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #17 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #18 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #19 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #20 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #21 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #22 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #23 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #24 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #25 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #26 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #27 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #28 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #29 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #30 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #31 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #32 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #33 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #34 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #35 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #36 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #37 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #38 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #39 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #40 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #41 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #42 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #43 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #44 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #45 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #46 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #47 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #48 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #49 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #50 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #51 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #52 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #53 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #54 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #55 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #56 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #57 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #58 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #59 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #60 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #61 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #62 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #63 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #64 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #65 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #66 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #67 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #68 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #69 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #70 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #71 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #72 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #73 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #74 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #75 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #76 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #77 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #78 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #79 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #80 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #81 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #82 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #83 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #84 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #85 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #86 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #87 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #88 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #89 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #90 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #91 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #92 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #93 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #94 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #95 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #96 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #97 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    #98 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    #99 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#100](/reports/100) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#101](/reports/101) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#102](/reports/102) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#103](/reports/103) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#104](/reports/104) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#105](/reports/105) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#106](/reports/106) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#107](/reports/107) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#108](/reports/108) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#109](/reports/109) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#110](/reports/110) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#111](/reports/111) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#112](/reports/112) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#113](/reports/113) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#114](/reports/114) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#115](/reports/115) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#116](/reports/116) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#117](/reports/117) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#118](/reports/118) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#119](/reports/119) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#120](/reports/120) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#121](/reports/121) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#122](/reports/122) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#123](/reports/123) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#124](/reports/124) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#125](/reports/125) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#126](/reports/126) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#127](/reports/127) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#128](/reports/128) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#129](/reports/129) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#130](/reports/130) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#131](/reports/131) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#132](/reports/132) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#133](/reports/133) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#134](/reports/134) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#135](/reports/135) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#136](/reports/136) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#137](/reports/137) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#138](/reports/138) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#139](/reports/139) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#140](/reports/140) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#141](/reports/141) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#142](/reports/142) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#143](/reports/143) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#144](/reports/144) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#145](/reports/145) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#146](/reports/146) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#147](/reports/147) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#148](/reports/148) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#149](/reports/149) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#150](/reports/150) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#151](/reports/151) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#152](/reports/152) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#153](/reports/153) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#154](/reports/154) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#155](/reports/155) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#156](/reports/156) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#157](/reports/157) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#158](/reports/158) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#159](/reports/159) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#160](/reports/160) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#161](/reports/161) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#162](/reports/162) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#163](/reports/163) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#164](/reports/164) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#165](/reports/165) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#166](/reports/166) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#167](/reports/167) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#168](/reports/168) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#169](/reports/169) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#170](/reports/170) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#171](/reports/171) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#172](/reports/172) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#173](/reports/173) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#174](/reports/174) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#175](/reports/175) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#176](/reports/176) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#177](/reports/177) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#178](/reports/178) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#179](/reports/179) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#180](/reports/180) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#181](/reports/181) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#182](/reports/182) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#183](/reports/183) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#184](/reports/184) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#185](/reports/185) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#186](/reports/186) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#187](/reports/187) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#188](/reports/188) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#189](/reports/189) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#190](/reports/190) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#191](/reports/191) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#192](/reports/192) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#193](/reports/193) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#194](/reports/194) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#195](/reports/195) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#196](/reports/196) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#197](/reports/197) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#198](/reports/198) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#199](/reports/199) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#200](/reports/200) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#201](/reports/201) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#202](/reports/202) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#203](/reports/203) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#204](/reports/204) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#205](/reports/205) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#206](/reports/206) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#207](/reports/207) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#208](/reports/208) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#209](/reports/209) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#210](/reports/210) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#211](/reports/211) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#212](/reports/212) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#213](/reports/213) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#214](/reports/214) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#215](/reports/215) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#216](/reports/216) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#217](/reports/217) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#218](/reports/218) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#219](/reports/219) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#220](/reports/220) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#221](/reports/221) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#222](/reports/222) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#223](/reports/223) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#224](/reports/224) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#225](/reports/225) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#226](/reports/226) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#227](/reports/227) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#228](/reports/228) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#229](/reports/229) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#230](/reports/230) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#231](/reports/231) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#232](/reports/232) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#233](/reports/233) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#234](/reports/234) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#235](/reports/235) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#236](/reports/236) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#237](/reports/237) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#238](/reports/238) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#239](/reports/239) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#240](/reports/240) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#241](/reports/241) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#242](/reports/242) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#243](/reports/243) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#244](/reports/244) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#245](/reports/245) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#246](/reports/246) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#247](/reports/247) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3
    [#248](/reports/248) 0x69a364 in codegen /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1533:5
    [#249](/reports/249) 0x6b1412 in gen_call /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:841:3

SUMMARY: AddressSanitizer: stack-overflow /home/fuzzer/git/mruby/mrbgems/mruby-compiler/core/codegen.c:1204 in codegen
==2865==ABORTING
```

**Comment by matz** [comment]
I think the issue was fixed by 45aadd7. But you may see the issue again for complex expressions.
We may need to add stack-depth check in code generation.

**Comment by clayton-shopify** [comment]
@matz Yes, I think that would be useful. Stack overflows in code generation can still occur, e.g. `ruby -e 'puts (["0"]*10000).join("+")' | bin/mruby`.

**Comment by matz** [comment]
fixed by fc7096f
