### ISSUE TITLE
Segfault in mrb_obj_iv_ifnone

### ISSUE THREAD

**Issue by clayton-shopify** [mruby/mruby#3435]
The following input demonstrates a crash when supplied to mirb: [203512.txt](https://github.com/mruby/mruby/files/755997/203512.txt)

I was able to reproduce the crash on Ubuntu 14.04 building with gcc, but not on OS X building with clang.

This issue was reported by https://hackerone.com/ston3

Some details about the crash:
```
$ gdb --args bin/mirb 203512.rb
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/mirb...done.
(gdb) run
Starting program: /home/clayton/git/mruby/bin/mirb 203512.rb
mirb - Embeddable Interactive Ruby Shell

 => nil
 => nil
 => nil
(mirb):4: undefined method 'a' for main (NoMethodError)
 => nil
 => ""
 => nil
 => nil
 => nil
 => nil

Program received signal SIGSEGV, Segmentation fault.
0x000000000043397d in get_file (info=0x461bb4 <mrb_int_chr>, pc=108231) at /home/clayton/git/mruby/src/debug.c:19
19	    if (!(pc < (*it)->start_pos)) {
(gdb) bt
#0  0x000000000043397d in get_file (info=0x461bb4 <mrb_int_chr>, pc=108231) at /home/clayton/git/mruby/src/debug.c:19
#1  0x0000000000433b37 in mrb_debug_get_filename (irep=0x6afe30, pc=108231) at /home/clayton/git/mruby/src/debug.c:58
#2  0x000000000041bf79 in each_backtrace (mrb=0x6ae010, ciidx=3, pc0=0x470820 <mrblib_irep+2456>, func=0x41c028 <output_backtrace_i>, data=0x7fffffffc7e0)
    at /home/clayton/git/mruby/src/backtrace.c:131
#3  0x000000000041c10a in output_backtrace (mrb=0x6ae010, ciidx=3, pc0=0x470820 <mrblib_irep+2456>, func=0x41bc55 <get_backtrace_i>, data=0x6b5da0)
    at /home/clayton/git/mruby/src/backtrace.c:181
#4  0x000000000041c1bf in exc_output_backtrace (mrb=0x6ae010, exc=0x6afa10, func=0x41bc55 <get_backtrace_i>, stream=0x6b5da0) at /home/clayton/git/mruby/src/backtrace.c:197
#5  0x000000000041c567 in mrb_exc_backtrace (mrb=0x6ae010, self=...) at /home/clayton/git/mruby/src/backtrace.c:299
#6  0x000000000042f23b in exc_get_backtrace (mrb=0x6ae010, exc=...) at /home/clayton/git/mruby/src/error.c:197
#7  0x000000000040c48b in mrb_vm_exec (mrb=0x6ae010, proc=0x6b60d0, pc=0x725794) at /home/clayton/git/mruby/src/vm.c:1211
#8  0x000000000040a941 in mrb_vm_run (mrb=0x6ae010, proc=0x6b60d0, self=..., stack_keep=2) at /home/clayton/git/mruby/src/vm.c:801
#9  0x0000000000402f3f in main (argc=2, argv=0x7fffffffe488) at /home/clayton/git/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c:549
```

**Comment by matz** [comment]
I couldn't reproduce the problem. Could you try valgrind?

**Comment by clayton-shopify** [comment]
```
$ valgrind -- bin/mirb 203512.rb 
==27364== Memcheck, a memory error detector
==27364== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==27364== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==27364== Command: bin/mirb 203512.rb
==27364== 
mirb - Embeddable Interactive Ruby Shell

 => nil
 => nil
 => nil
(mirb):4: undefined method 'a' for main (NoMethodError)
 => nil
 => ""
 => nil
 => nil
 => nil
 => nil
==27364== Invalid read of size 8
==27364==    at 0x41C678: get_file (debug.c:19)
==27364==    by 0x41C832: mrb_debug_get_filename (debug.c:58)
==27364==    by 0x4352C2: each_backtrace (backtrace.c:131)
==27364==    by 0x4354A2: output_backtrace (backtrace.c:181)
==27364==    by 0x43556E: exc_output_backtrace (backtrace.c:197)
==27364==    by 0x435942: mrb_exc_backtrace (backtrace.c:299)
==27364==    by 0x41AED6: exc_get_backtrace (error.c:197)
==27364==    by 0x40711B: mrb_vm_exec (vm.c:1211)
==27364==    by 0x4055C2: mrb_vm_run (vm.c:801)
==27364==    by 0x402DB9: main (mirb.c:549)
==27364==  Address 0x48f08948e87f9668 is not stack'd, malloc'd or (recently) free'd
==27364== 
==27364== 
==27364== Process terminating with default action of signal 11 (SIGSEGV)
==27364==  General Protection Fault
==27364==    at 0x41C678: get_file (debug.c:19)
==27364==    by 0x41C832: mrb_debug_get_filename (debug.c:58)
==27364==    by 0x4352C2: each_backtrace (backtrace.c:131)
==27364==    by 0x4354A2: output_backtrace (backtrace.c:181)
==27364==    by 0x43556E: exc_output_backtrace (backtrace.c:197)
==27364==    by 0x435942: mrb_exc_backtrace (backtrace.c:299)
==27364==    by 0x41AED6: exc_get_backtrace (error.c:197)
==27364==    by 0x40711B: mrb_vm_exec (vm.c:1211)
==27364==    by 0x4055C2: mrb_vm_run (vm.c:801)
==27364==    by 0x402DB9: main (mirb.c:549)
==27364== 
==27364== HEAP SUMMARY:
==27364==     in use at exit: 12,700,343 bytes in 717,000 blocks
==27364==   total heap usage: 722,671 allocs, 5,671 frees, 4,538,421,611 bytes allocated
==27364== 
==27364== LEAK SUMMARY:
==27364==    definitely lost: 0 bytes in 0 blocks
==27364==    indirectly lost: 0 bytes in 0 blocks
==27364==      possibly lost: 16,048 bytes in 2 blocks
==27364==    still reachable: 12,684,295 bytes in 716,998 blocks
==27364==         suppressed: 0 bytes in 0 blocks
==27364== Rerun with --leak-check=full to see details of leaked memory
==27364== 
==27364== For counts of detected and suppressed errors, rerun with: -v
==27364== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by clayton-shopify** [comment]
I was able to reproduce the above on Ubuntu 16.04 with clang.

**Comment by clayton-shopify** [comment]
@matz This behaviour seems to occur because the backtrace generation tries to access a proc that has already been garbage collected. This can be demonstrated with the following input:
```ruby
begin
  [0].each do
    [].each 0
  end
rescue=>e
end
#GC.start
puts e.backtrace
```
This produces the expected result:
```
$ bin/mruby 203512.rb 
["/home/argilo/git/mruby/mrblib/array.rb:12:in Array.each", "203512.rb:3:in Object.call", "203512.rb:8"]
```
But if you uncomment the `#GC.start` line, then the result is incorrect:
```
$ bin/mruby 203512.rb 
["/home/argilo/git/mruby/mrblib/array.rb:12:in Array.each", "203512.rb:8"]
```
Adding a call to `e.backtrace` inside the `rescue` clause results in the correct output again, since the backtrace is cached.

**Comment by matz** [comment]
Probably the problem has been fixed.

**Comment by clayton-shopify** [comment]
@matz Garbage collection is still causing the output of `backtrace` to change:
```
$ bin/mruby
begin
  [0].each do
    [].each 0
  end
rescue=>e
end
#GC.start
puts e.backtrace

["/Users/clayton/git/mruby/mrblib/array.rb:12:in Array.each", "-:3:in Object.call", "-:8"]
```
```
$ bin/mruby
begin
  [0].each do
    [].each 0
  end
rescue=>e
end
GC.start
puts e.backtrace

["/Users/clayton/git/mruby/mrblib/array.rb:12:in Array.each", "-:8"]
```
Does that mean there's still a problem?

**Comment by clayton-shopify** [comment]
https://hackerone.com/icanthack pointed out that this slight variation still demonstrates a crash:
```ruby
begin
  [0].each do
    ['00'].each 0
  end
rescue=>e
end
GC.start
e.backtrace
```
Output:
```
Assertion failed: (info->files <= ret && ret < (info->files + info->flen)), function get_file, file /Users/clayton/git/mruby/src/debug.c, line 29.
Abort trap: 6
```

**Comment by clayton-shopify** [comment]
@matz It looks like 05fceb5992c20c30a6b31f89d2b0aa0f0698a9a2 fixed this.

**Comment by matz** [comment]
May I close the issue?

**Comment by clayton-shopify** [comment]
Yes. I've confirmed the issue is now fixed.
