### ISSUE TITLE
Bugs with mutually recursive Array and Hash

### ISSUE THREAD

**Issue by lopopolo** [mruby/mruby#4582]
Mutually recursive array fails to hash with a `SystemStackError`:

```
> a1 = []
 => []
> a2 = [a1]
 => [[]]
> a1 << a2; nil
 => nil
> a1.hash
(mirb):4: stack level too deep (SystemStackError)
> a2.hash
(mirb):4: stack level too deep (SystemStackError)
```

Hash with recursive key fails to hash with a `SystemStackError`:

```
> ary = []
 => []
> hash = { ary => ary }
 => {[]=>[]}
> hash[hash] = 1; nil
 => nil
> hash.hash
(mirb):4: stack level too deep (SystemStackError)
```

Hash with recursive value fails to hash with `SystemStackError`:

```
> ary = []
 => []
> hash = { ary => ary }
 => {[]=>[]}
> hash[1] = hash; nil
 => nil
> hash.inspect
 => "{...}"
> hash.hash
(mirb):4: stack level too deep (SystemStackError)
```

Mutually recursive array infinite loop on inspect:

```
> ary = []
 => []
> hash = { ary => ary }
 => {[]=>[]}
> ary << hash; nil
 => nil
> ary.inspect
^C
```

Mutually recursive Hash infinite loop on inspect:

```
> ary = []
 => []
> hash = { ary => ary }
 => {[]=>[]}
> ary << hash; nil
 => nil
> hash.inspect
^C
```

**Comment by matz** [comment]
#4034 merged. This issue is addressed as well.

**Comment by lopopolo** [comment]
`Array#hash` and `Hash#hash` still fail with `SystemStackError` with this fix:

```console
$ ./bin/mirb
mirb - Embeddable Interactive Ruby Shell

> ary = []
 => []
> hash = { ary => ary }
 => {[]=>[]}
> ary << hash; nil
 => nil
> ary.inspect
 => "[{[...]=>[...]}]"
> hash.inspect
 => "{[{...}]=>[...]}"
> ary.hash
(mirb):6: stack level too deep (SystemStackError)
> hash.hash
(mirb):6: stack level too deep (SystemStackError)
```

**Comment by matz** [comment]
SystemStackError is intentional. We tried to avoid real infinite loop.
